# Generated by Django 5.0.2 on 2024-02-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_delete_customuseradmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
