# Generated by Django 3.2.23 on 2023-12-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20231228_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/defalt.jpg', upload_to='blog/'),
        ),
    ]
